name: delt-hit
channels:
  - defaults
dependencies:
  - bzip2=1.0.8=h80987f9_6
  - c-ares=1.34.6=hfe05a68_0
  - ca-certificates=2025.12.2=hca03da5_0
  - cairo=1.18.4=h191e429_0
  - expat=2.7.4=h50f4ffc_0
  - font-ttf-dejavu-sans-mono=2.37=hd3eb1b0_0
  - font-ttf-inconsolata=2.001=hcb22688_0
  - font-ttf-source-code-pro=2.030=hd3eb1b0_0
  - font-ttf-ubuntu=0.83=h8b1ccd4_0
  - fontconfig=2.15.0=h29935d0_0
  - fonts-anaconda=1=h8fa9717_0
  - fonts-conda-ecosystem=1=hd3eb1b0_0
  - freetype=2.14.1=h7cdc921_0
  - fribidi=1.0.16=h8859324_0
  - gdk-pixbuf=2.42.10=h969f7ef_2
  - gettext=0.21.0=hbdbcc25_2
  - giflib=5.2.2=h80987f9_0
  - glib=2.86.3=h863a760_0
  - glib-tools=2.86.3=hff4a405_0
  - graphite2=1.3.14=hc377ac9_1
  - graphviz=12.2.1=hd400d58_2
  - gts=0.7.6=hde733a8_3
  - harfbuzz=10.2.0=he637ebf_1
  - icu=73.1=h313beb8_0
  - jansson=2.14=h80987f9_1
  - jpeg=9f=h2f69dba_0
  - lcms2=2.17=h7418793_0
  - lerc=4.0.0=h313beb8_0
  - libboost=1.88.0=hb389264_0
  - libbrotlicommon=1.2.0=hbd7815e_0
  - libbrotlidec=1.2.0=h1e834b2_0
  - libbrotlienc=1.2.0=h5439a07_0
  - libcurl=8.18.0=hd4c70c6_0
  - libcxx=21.1.8=hb4ce287_0
  - libdeflate=1.22=h80987f9_0
  - libev=4.33=h1a28f6b_1
  - libexpat=2.7.4=h50f4ffc_0
  - libffi=3.4.4=hca03da5_1
  - libgd=2.3.3=hd3b0a14_4
  - libglib=2.86.3=hcacd345_0
  - libiconv=1.16=h80987f9_3
  - libidn2=2.3.8=h9681e36_0
  - libkrb5=1.22.1=ha46c28b_0
  - libltdl=2.6.0=haa24f5a_0
  - libnghttp2=1.67.1=h8189af8_0
  - libopenjpeg=2.5.4=haa24f5a_1
  - libpng=1.6.54=h5c318fc_0
  - librsvg=2.56.3=h38920c8_2
  - libssh2=1.11.1=h3e2b118_0
  - libtiff=4.7.1=h367c460_0
  - libtool=2.6.0=h50f4ffc_0
  - libunistring=1.3=h1799b2a_0
  - libwebp=1.6.0=h30d73d9_0
  - libwebp-base=1.6.0=h92b2d59_0
  - libxml2=2.13.9=h528a072_0
  - libzlib=1.3.1=h5f15de7_0
  - llvm-openmp=20.1.8=he822017_0
  - lmdb=0.9.31=h79febb2_0
  - lz4-c=1.9.4=h313beb8_1
  - ncurses=6.5=hee39554_0
  - nspr=4.37=hd3a7ab8_0
  - nss=3.117=hfbaeeee_0
  - openjpeg=2.5.4=h959fc53_1
  - openssl=3.0.19=ha0b305a_0
  - packaging=25.0=py312hca03da5_1
  - pango=1.50.7=hf2328af_2
  - pcre2=10.46=h1dacb4a_0
  - pip=25.3=pyhc872135_0
  - pixman=0.46.4=h09dc60e_0
  - poppler=24.09.0=h10a2f5c_4
  - poppler-data=0.4.12=hca03da5_0
  - pygraphviz=1.14=py312h80987f9_1
  - python=3.12.12=h2bfc596_1
  - readline=8.3=h0b18652_0
  - sqlite=3.51.1=hab6afd1_0
  - tk=8.6.15=hcd8a7d5_0
  - xz=5.6.4=h80987f9_1
  - zlib=1.3.1=h5f15de7_0
  - zstd=1.5.7=h817c040_0
  - pip:
      - annotated-types==0.7.0
      - blinker==1.9.0
      - certifi==2025.8.3
      - charset-normalizer==3.4.3
      - click==8.3.0
      - contourpy==1.3.3
      - cutadapt==5.1
      - cycler==0.12.1
      - dash==2.18.2
      - dash-core-components==2.0.0
      - dash-html-components==2.0.0
      - dash-table==5.0.0
      - delt-hit==0.0.1
      - dnaio==1.2.3
      - et-xmlfile==2.0.0
      - filelock==3.19.1
      - flask==3.0.3
      - fonttools==4.60.0
      - fsspec==2025.9.0
      - hf-xet==1.1.10
      - huggingface-hub==0.35.1
      - idna==3.10
      - importlib-metadata==8.7.0
      - itsdangerous==2.2.0
      - jinja2==3.1.6
      - jsonargparse==4.41.0
      - kiwisolver==1.4.9
      - levenshtein==0.27.1
      - loguru==0.7.3
      - markdown-it-py==4.0.0
      - markupsafe==3.0.2
      - matplotlib==3.10.6
      - mdurl==0.1.2
      - mpmath==1.3.0
      - narwhals==2.5.0
      - nest-asyncio==1.6.0
      - networkx==3.5
      - numpy==2.3.3
      - openpyxl==3.1.5
      - pandas==2.3.2
      - pillow==11.3.0
      - plotly==6.3.0
      - pyaml==25.7.0
      - pyarrow==21.0.0
      - pydantic==2.11.9
      - pydantic-core==2.33.2
      - pydantic-settings==2.10.1
      - pygments==2.19.2
      - pyparsing==3.2.4
      - python-dateutil==2.9.0.post0
      - python-dotenv==1.1.1
      - pytz==2025.2
      - pyyaml==6.0.2
      - rapidfuzz==3.14.1
      - rdkit==2025.3.6
      - regex==2025.9.18
      - requests==2.32.5
      - retrying==1.4.2
      - rich==14.1.0
      - safetensors==0.6.2
      - scipy==1.16.2
      - seaborn==0.13.2
      - setuptools==78.1.1
      - six==1.17.0
      - sympy==1.14.0
      - tabulate==0.9.0
      - tokenizers==0.22.1
      - torch==2.8.0
      - tqdm==4.67.1
      - transformers==4.56.2
      - typing-extensions==4.15.0
      - typing-inspection==0.4.1
      - tzdata==2025.2
      - urllib3==2.5.0
      - werkzeug==3.0.6
      - wheel==0.45.1
      - xopen==2.0.2
      - zipp==3.23.0
