experiment:
  name: experiment-rechecked-enum
  fastq_path: /Users/adrianomartinelli/Library/CloudStorage/OneDrive-ETHZurich/oneDrive-documents/data/DECLT-DB/fastq_files/368061_1-241105_AG_BZ_NC_pool1_NF_S3_R1_001.fastq.gz
  save_dir: /Users/adrianomartinelli/projects/delt/delt-core/paper/
  num_cores: 11
  .nan: f
library:
  products:
  - converted_1B
  - precursor_1
  - product_1
  - product_1B
  - product_2
  - scaffold_7
  steps:
  - - ABF
    - product_1
  - - B0
    - ABF
  - - B0
    - CuAAC
  - - B0
    - SR
  - - B1
    - DH
  - - B1
    - PASS
  - - B1
    - Son
  - - B1
    - Suz
  - - CuAAC
    - product_1
  - - CuAAC
    - product_1B
  - - DH
    - product_2
  - - PASS
    - product_2
  - - PASS_0
    - precursor_1
  - - PASS_1
    - converted_1B
  - - PASS_3
    - scaffold_7
  - - SR
    - product_1
  - - Son
    - product_2
  - - Suz
    - product_2
  - - converted_1B
    - Suz
  - - precursor_0
    - PASS_0
  - - precursor_1
    - PASS_3
  - - product_1
    - DH
  - - product_1
    - PASS
  - - product_1
    - Son
  - - product_1B
    - PASS_1
  - - scaffold_1
    - CuAAC
  - - scaffold_1
    - SR
  - - scaffold_2
    - SR
  - - scaffold_4
    - ABF
  - - scaffold_5
    - ABF
  - - scaffold_7
    - ABF
  building_blocks:
  - B0
  - B1
catalog:
  compounds:
    scaffold_1:
      smiles: Ic1ccc(CC(N=[N+]=[N-])C(O)=O)cc1
      orientation: o
    scaffold_2:
      smiles: '[N-]=[N+]=NC(C(O)=O)Cc1cc(I)ccc1'
      orientation: p
    scaffold_3:
      smiles: '[N-]=[N+]=NC(C(O)=O)Cc1c(I)cccc1'
      orientation: m
    scaffold_4:
      smiles: NC(Cc1ccc(I)cc1)C(=O)O
      orientation: p
    scaffold_5:
      smiles: NC(Cc1cccc(I)c1)C(=O)O
      orientation: m
    scaffold_6:
      smiles: NC(Cc1ccccc1I)C(=O)O
      orientation: o
    precursor_0:
      smiles: NC(Cc1ccccc1I)C(=O)O
      orientation: .nan
  reactions:
    ABF:
      smirks: '[CX3:1](=[O:2])[OX2;H1].[N;H2:4]>>[CX3:1](=[O:2])[N;H:4]'
    SR:
      smirks: '[#6:1][$([NX2-][NX2+]#[NX1]),$([NX2]=[NX2+]=[NX1-])]>>[#6:1][N;H2]'
    CuAAC:
      smirks: '[CX2:1]#[CX2;H1:2].[N:3]=[N+:4]=[N-:5]>>[C:1]1=[C:2][N-0:3][N-0:4]=[N-0:5]1'
    Suz:
      smirks: '[cX3:1][I].[#6:2][BX3]>>[cX3:1][#6:2]'
    Son:
      smirks: '[cX3:1][I].[CX2:2]#[CX2;H1:3]>>[cX3:1]-[CX2:3]#[CX2:2]'
    DH:
      smirks: '[cX3:1][I]>>[cX3;H1:1]'
    DT:
      smirks: '[#6:1][N;H2:2]>>[#6:1][N:2]=[N+]=[N-]'
    SN2-1:
      smirks: ([#6:1][S;H1:2].[C;H2:3][Cl,Br])>>[#6:1][S:2][C;H2:3]
    SN2-2:
      smirks: '[#6:1][S;H1:2].[C;H2:3][Cl,Br]>>[#6:1][S:2][C;H2:3]'
    CuAACv2:
      smirks: '[c:1]I.[#6:2][B](O)O>>[c:1][#6:2]'
    PASS:
      smirks: .nan
    PASS_0:
      smirks: .nan
    PASS_1:
      smirks: .nan
    PASS_3:
      smirks: .nan
structure:
- name: S0
  type: selection
  max_error_rate: 0
  indels: false
- name: C0
  type: constant
  max_error_rate: 0
  indels: false
- name: B0
  type: building_block
  max_error_rate: 0
  indels: false
- name: C1
  type: constant
  max_error_rate: 0
  indels: false
- name: B1
  type: building_block
  max_error_rate: 0
  indels: false
- name: C2
  type: constant
  max_error_rate: 0
  indels: false
- name: S1
  type: selection
  max_error_rate: 0
  indels: false
selections:
  AG24_1:
    operator: A. Gloger
    date: '2024-09-26'
    target: No Protein
    group: no_protein
    beads: Dynabeads SA C1
    info: '-'
    blocking: Biotin
    buffer: PBS-T
    protocol: DECL_5W
    S0: ACACAC
    S1: CGCTCGATA
    ids:
    - 0
    - 0
  AG24_2:
    operator: A. Gloger
    date: '2024-09-26'
    target: No Protein
    group: no_protein
    beads: Dynabeads SA C1
    info: '-'
    blocking: Biotin
    buffer: PBS-T
    protocol: DECL_5W
    S0: ACAGCA
    S1: CGCTCGATA
    ids:
    - 1
    - 0
  AG24_3:
    operator: A. Gloger
    date: '2024-09-26'
    target: No Protein
    group: no_protein
    beads: Dynabeads SA C1
    info: '-'
    blocking: Biotin
    buffer: PBS-T
    protocol: DECL_5W
    S0: ACATGT
    S1: CGCTCGATA
    ids:
    - 2
    - 0
  AG24_10:
    operator: A. Gloger
    date: '2024-09-26'
    target: hCAII-Avi-His (biot)
    group: protein
    beads: Dynabeads SA C1
    info: '-'
    blocking: Biotin
    buffer: PBS-T
    protocol: DECL_5W
    S0: ACGACG
    S1: CGCTCGATA
    ids:
    - 3
    - 0
  AG24_11:
    operator: A. Gloger
    date: '2024-09-26'
    target: hCAII-Avi-His (biot)
    group: protein
    beads: Dynabeads SA C1
    info: '-'
    blocking: Biotin
    buffer: PBS-T
    protocol: DECL_5W
    S0: ACGCGA
    S1: CGCTCGATA
    ids:
    - 4
    - 0
  AG24_12:
    operator: A. Gloger
    date: '2024-09-26'
    target: hCAII-Avi-His (biot)
    group: protein
    beads: Dynabeads SA C1
    info: '-'
    blocking: Biotin
    buffer: PBS-T
    protocol: DECL_5W
    S0: ACTAGC
    S1: CGCTCGATA
    ids:
    - 5
    - 0
  AG24_19:
    operator: A. Gloger
    date: '2024-09-26'
    target: USP-13 (biot.)
    group: protein
    beads: Dynabeads SA C1
    info: '-'
    blocking: Biotin
    buffer: PBS-T
    protocol: DECL_5W
    S0: ACTCTG
    S1: CGCTCGATA
    ids:
    - 6
    - 0
  AG24_20:
    operator: A. Gloger
    date: '2024-09-26'
    target: USP-13 (biot.)
    group: protein
    beads: Dynabeads SA C1
    info: '-'
    blocking: Biotin
    buffer: PBS-T
    protocol: DECL_5W
    S0: ACTGAT
    S1: CGCTCGATA
    ids:
    - 7
    - 0
  AG24_21:
    operator: A. Gloger
    date: '2024-09-26'
    target: USP-13 (biot.)
    group: protein
    beads: Dynabeads SA C1
    info: '-'
    blocking: Biotin
    buffer: PBS-T
    protocol: DECL_5W
    S0: AGACTA
    S1: CGCTCGATA
    ids:
    - 8
    - 0
  AG24_28:
    operator: A. Gloger
    date: '2024-09-26'
    target: No Protein
    group: no_protein
    beads: Dynabeads SA C1
    info: '-'
    blocking: Biotin
    buffer: Tris-T
    protocol: DECL_5W
    S0: AGAGAG
    S1: CGCTCGATA
    ids:
    - 9
    - 0
  AG24_29:
    operator: A. Gloger
    date: '2024-09-26'
    target: No Protein
    group: no_protein
    beads: Dynabeads SA C1
    info: '-'
    blocking: Biotin
    buffer: Tris-T
    protocol: DECL_5W
    S0: TAGATG
    S1: CGCTCGATA
    ids:
    - 10
    - 0
  AG24_30:
    operator: A. Gloger
    date: '2024-09-26'
    target: No Protein
    group: no_protein
    beads: Dynabeads SA C1
    info: '-'
    blocking: Biotin
    buffer: Tris-T
    protocol: DECL_5W
    S0: TAGTGT
    S1: CGCTCGATA
    ids:
    - 11
    - 0
  AG24_37:
    operator: A. Gloger
    date: '2024-09-26'
    target: USP-10 (biot.)
    group: protein
    beads: Dynabeads SA C1
    info: '-'
    blocking: Biotin
    buffer: Tris-T
    protocol: DECL_5W
    S0: TATCAC
    S1: CGCTCGATA
    ids:
    - 12
    - 0
  AG24_38:
    operator: A. Gloger
    date: '2024-09-26'
    target: USP-10 (biot.)
    group: protein
    beads: Dynabeads SA C1
    info: '-'
    blocking: Biotin
    buffer: Tris-T
    protocol: DECL_5W
    S0: TCATAG
    S1: CGCTCGATA
    ids:
    - 13
    - 0
  AG24_39:
    operator: A. Gloger
    date: '2024-09-26'
    target: USP-10 (biot.)
    group: protein
    beads: Dynabeads SA C1
    info: '-'
    blocking: Biotin
    buffer: Tris-T
    protocol: DECL_5W
    S0: TCGTCA
    S1: CGCTCGATA
    ids:
    - 14
    - 0
  AG24_46:
    operator: A. Gloger
    date: '2024-09-26'
    target: PTEN (biot.)
    group: protein
    beads: Dynabeads SA C1
    info: '-'
    blocking: Biotin
    buffer: Tris-T
    protocol: DECL_5W
    S0: TCTACT
    S1: CGCTCGATA
    ids:
    - 15
    - 0
  AG24_47:
    operator: A. Gloger
    date: '2024-09-26'
    target: PTEN (biot.)
    group: protein
    beads: Dynabeads SA C1
    info: '-'
    blocking: Biotin
    buffer: Tris-T
    protocol: DECL_5W
    S0: TCTGTA
    S1: CGCTCGATA
    ids:
    - 16
    - 0
  AG24_48:
    operator: A. Gloger
    date: '2024-09-26'
    target: PTEN (biot.)
    group: protein
    beads: Dynabeads SA C1
    info: '-'
    blocking: Biotin
    buffer: Tris-T
    protocol: DECL_5W
    S0: TGACAT
    S1: CGCTCGATA
    ids:
    - 17
    - 0
  AG24_55:
    operator: A. Gloger
    date: '2024-10-17'
    target: No Protein
    group: no_protein
    beads: Streptactin-Beads (MagStrep "type3" XT beads, 5% suspension)
    info: '-'
    blocking: .nan
    buffer: HEPES-T
    protocol: DECL_5W
    S0: TGCAGC
    S1: CGCTCGATA
    ids:
    - 18
    - 0
  AG24_56:
    operator: A. Gloger
    date: '2024-10-17'
    target: No Protein
    group: no_protein
    beads: Streptactin-Beads (MagStrep "type3" XT beads, 5% suspension)
    info: '-'
    blocking: .nan
    buffer: HEPES-T
    protocol: DECL_5W
    S0: TGCGCG
    S1: CGCTCGATA
    ids:
    - 19
    - 0
  AG24_57:
    operator: A. Gloger
    date: '2024-10-17'
    target: No Protein
    group: no_protein
    beads: Streptactin-Beads (MagStrep "type3" XT beads, 5% suspension)
    info: '-'
    blocking: .nan
    buffer: HEPES-T
    protocol: DECL_5W
    S0: GCTACT
    S1: CGCTCGATA
    ids:
    - 20
    - 0
  AG24_64:
    operator: A. Gloger
    date: '2024-10-17'
    target: GYS:GYG1 (TwinStrept)
    group: protein
    beads: Streptactin-Beads (MagStrep "type3" XT beads, 5% suspension)
    info: Substrate (G6P)
    blocking: .nan
    buffer: HEPES-T
    protocol: DECL_5W
    S0: GCACAT
    S1: CGCTCGATA
    ids:
    - 21
    - 0
  AG24_65:
    operator: A. Gloger
    date: '2024-10-17'
    target: GYS:GYG1 (TwinStrept)
    group: protein
    beads: Streptactin-Beads (MagStrep "type3" XT beads, 5% suspension)
    info: Substrate (G6P)
    blocking: .nan
    buffer: HEPES-T
    protocol: DECL_5W
    S0: GAGTGT
    S1: CGCTCGATA
    ids:
    - 22
    - 0
  AG24_66:
    operator: A. Gloger
    date: '2024-10-17'
    target: GYS:GYG1 (TwinStrept)
    group: protein
    beads: Streptactin-Beads (MagStrep "type3" XT beads, 5% suspension)
    info: Substrate (G6P)
    blocking: .nan
    buffer: HEPES-T
    protocol: DECL_5W
    S0: GTGCGA
    S1: CGCTCGATA
    ids:
    - 23
    - 0
  AG24_73:
    operator: A. Gloger
    date: '2024-10-17'
    target: GYS:GYG1 (TwinStrept)
    group: protein
    beads: Streptactin-Beads (MagStrep "type3" XT beads, 5% suspension)
    info: (G6P) + Analog23
    blocking: .nan
    buffer: HEPES-T
    protocol: DECL_5W
    S0: GCCGCT
    S1: CGCTCGATA
    ids:
    - 24
    - 0
  AG24_74:
    operator: A. Gloger
    date: '2024-10-17'
    target: GYS:GYG1 (TwinStrept)
    group: protein
    beads: Streptactin-Beads (MagStrep "type3" XT beads, 5% suspension)
    info: (G6P) + Analog23
    blocking: .nan
    buffer: HEPES-T
    protocol: DECL_5W
    S0: GAAGAT
    S1: CGCTCGATA
    ids:
    - 25
    - 0
  AG24_75:
    operator: A. Gloger
    date: '2024-10-17'
    target: GYS:GYG1 (TwinStrept)
    group: protein
    beads: Streptactin-Beads (MagStrep "type3" XT beads, 5% suspension)
    info: (G6P) + Analog23
    blocking: .nan
    buffer: HEPES-T
    protocol: DECL_5W
    S0: GTTCAG
    S1: CGCTCGATA
    ids:
    - 26
    - 0
whitelists:
  C0:
  - codon: GGAGCTTCTGAATTCTGTGTGCTG
  C1:
  - codon: CGAGTCCCATGGCGCCGGATCGACG
  C2:
  - codon: GCGTCAGGCAGC
  B0:
  - index: 0
    smiles: OC(=O)C1=CC(=CN=C1)C#C
    codon: GCCTCG
    reaction: CuAAC
    reactant: scaffold_1
    product: product_1
  - index: 1
    smiles: OC(=O)C1=CC(=CN=C1)C#C
    codon: GCCTCG
    reaction: CuAAC
    reactant: scaffold_1
    product: product_1B
  - index: 2
    smiles: .nan
    codon: AACCTG
    reaction: SR
    reactant: scaffold_1
    product: product_1
  - index: 3
    smiles: CCC=CCC(O)=O
    codon: TGGTAA
    reaction: ABF
    reactant: scaffold_4
    product: product_1
  - index: 4
    smiles: .nan
    codon: TGCCGT
    reaction: SR
    reactant: scaffold_2
    product: product_1
  - index: 5
    smiles: CCC=CCC(O)=O
    codon: AACGGA
    reaction: ABF
    reactant: scaffold_5
    product: product_1
  - index: 6
    smiles: CCC=CCC(O)=O
    codon: GGACGC
    reaction: ABF
    reactant: scaffold_7
    product: product_1
  B1:
  - index: 0
    smiles: OB(O)c1cc(ccc1Cl)C#N
    codon: GTCTCAC
    reaction: Suz
    reactant: converted_1B
    product: product_2
  - index: 1
    smiles: COc1ccc(B(O)O)c(F)c1
    codon: GTCGTAC
    reaction: Suz
    reactant: converted_1B
    product: product_2
  - index: 2
    smiles: C#CCN1C=CC2=C1C=CC=C2
    codon: GAACCGT
    reaction: Son
    reactant: product_1
    product: product_2
  - index: 3
    smiles: ClC1=C(NC(=O)NCC#C)C=CC=C1
    codon: AATCGTT
    reaction: Son
    reactant: product_1
    product: product_2
  - index: 4
    smiles: .nan
    codon: TGTTGCT
    reaction: DH
    reactant: product_1
    product: product_2
  - index: 5
    smiles: .nan
    codon: TGGCAAT
    reaction: PASS
    reactant: product_1
    product: product_2
  S0:
  - name: AG24_1
    codon: ACACAC
  - name: AG24_2
    codon: ACAGCA
  - name: AG24_3
    codon: ACATGT
  - name: AG24_10
    codon: ACGACG
  - name: AG24_11
    codon: ACGCGA
  - name: AG24_12
    codon: ACTAGC
  - name: AG24_19
    codon: ACTCTG
  - name: AG24_20
    codon: ACTGAT
  - name: AG24_21
    codon: AGACTA
  - name: AG24_28
    codon: AGAGAG
  - name: AG24_29
    codon: TAGATG
  - name: AG24_30
    codon: TAGTGT
  - name: AG24_37
    codon: TATCAC
  - name: AG24_38
    codon: TCATAG
  - name: AG24_39
    codon: TCGTCA
  - name: AG24_46
    codon: TCTACT
  - name: AG24_47
    codon: TCTGTA
  - name: AG24_48
    codon: TGACAT
  - name: AG24_55
    codon: TGCAGC
  - name: AG24_56
    codon: TGCGCG
  - name: AG24_57
    codon: GCTACT
  - name: AG24_64
    codon: GCACAT
  - name: AG24_65
    codon: GAGTGT
  - name: AG24_66
    codon: GTGCGA
  - name: AG24_73
    codon: GCCGCT
  - name: AG24_74
    codon: GAAGAT
  - name: AG24_75
    codon: GTTCAG
  S1:
  - name: AG24_1
    codon: CGCTCGATA
  - name: AG24_2
    codon: CGCTCGATA
  - name: AG24_3
    codon: CGCTCGATA
  - name: AG24_10
    codon: CGCTCGATA
  - name: AG24_11
    codon: CGCTCGATA
  - name: AG24_12
    codon: CGCTCGATA
  - name: AG24_19
    codon: CGCTCGATA
  - name: AG24_20
    codon: CGCTCGATA
  - name: AG24_21
    codon: CGCTCGATA
  - name: AG24_28
    codon: CGCTCGATA
  - name: AG24_29
    codon: CGCTCGATA
  - name: AG24_30
    codon: CGCTCGATA
  - name: AG24_37
    codon: CGCTCGATA
  - name: AG24_38
    codon: CGCTCGATA
  - name: AG24_39
    codon: CGCTCGATA
  - name: AG24_46
    codon: CGCTCGATA
  - name: AG24_47
    codon: CGCTCGATA
  - name: AG24_48
    codon: CGCTCGATA
  - name: AG24_55
    codon: CGCTCGATA
  - name: AG24_56
    codon: CGCTCGATA
  - name: AG24_57
    codon: CGCTCGATA
  - name: AG24_64
    codon: CGCTCGATA
  - name: AG24_65
    codon: CGCTCGATA
  - name: AG24_66
    codon: CGCTCGATA
  - name: AG24_73
    codon: CGCTCGATA
  - name: AG24_74
    codon: CGCTCGATA
  - name: AG24_75
    codon: CGCTCGATA
